language: python
python:
 # - "2.6"
  - "2.7"
#  - "3.3"
 # - "3.4"
#  - "pypy"

before_install:
  - sudo apt-get update
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-de
  - sudo apt-get install swig
install:
  - travis_retry pip install -r requirements-py26.txt
  - travis_retry pip install -r requirements.txt

script: python tests/test.py --with-coverage -c tests/db
#script: nosetests tests/
#cache: true
