language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.3"
  #- "3.4"
  #- "pypy"
before_install:
  - shippable_retry sudo apt-get update
  - shippable_retry sudo apt-get --reinstall install -qq language-pack-en language-pack-de
  - shippable_retry sudo apt-get install swig
  
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

install:
  - travis_retry pip install -r requirements-py26.txt
  - shippable_retry pip install -r requirements.txt
  
script: 
  - python tests/test.py default --with-coverage --cover-package=tests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  #- nosetests tests/integration/*/*.py --with-xunit --xunit-file=shippable/testresults/nosetests.xml
#  - which python && coverage run --branch tests/test.py unit
  - coverage xml -o shippable/codecoverage/coverage.xml 
  
archive: true
#parallelized_test : true
cache: true
