language: python
python:
  #- "2.6"
  - "2.7"
 # - "3.3"
  #- "3.4"
  #- "pypy"
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get --reinstall install -qq language-pack-en language-pack-de
  - travis_retry sudo apt-get install swig
  

install:
  - travis_retry pip install -r requirements-py26.txt
  - travis_retry pip install -r requirements.txt
  
script: 
  - python tests/test.py 
  
